
import javax.swing.JTable;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author oyi
 */
public class mobilview extends javax.swing.JFrame {

    /**
     * Creates new form mobilview
     */
    public mobilview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        datalatih = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        datauji = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        normaluji = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        normallatih = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        Dinput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lamdainput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        konstanta = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cinput = new javax.swing.JTextField();
        alpaawal = new javax.swing.JTextField();
        epsiloninput = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        itermax = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        kernel1 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        Thesian = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tei = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Twx = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        Txminxpos = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        Tfx = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        nilaibias = new javax.swing.JTextField();
        pengumuman = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("svm mobil");
        setSize(new java.awt.Dimension(1200, 768));

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"D1", 4.0, 1.65, 1.7, 1},
                {"D2", 3.9, 1.6, 1.8, 1},
                {"D3", 4.4, 1.5, 1.8, 1},
                {"D4", 3.8, 1.7, 1.9, -1},
                {"D5", 4.0, 1.6, 1.7, -1},
                {"D6", 4.2, 1.7, 1.8, 1},
                {"D7", 4.1, 1.8, 1.8, -1},
                {"D8", 3.9, 1.65, 1.7, -1},
                {"D9", 3.8, 1.5, 1.8, 1},
                {"D10", 4.0, 1.8, 1.7, 1},
                {"D11", 4.1, 1.7, 1.8, -1},
                {"D12", 4.0, 1.6, 1.8, 1}
            },
            new String [] {
                "ID", "Panjang (x1)", "Tinggi (x2)", "Lebar (x3)", "Kelas"
            }
        ));
        jScrollPane2.setViewportView(data);

        jLabel1.setText("Data set Mobil");

        datalatih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {data.getModel().getValueAt(0, 0), data.getModel().getValueAt(0, 1),data.getModel().getValueAt(0, 2), data.getModel().getValueAt(0, 3), data.getModel().getValueAt(0, 4)},
                {data.getModel().getValueAt(1, 0), data.getModel().getValueAt(1, 1),data.getModel().getValueAt(1, 2), data.getModel().getValueAt(1, 3), data.getModel().getValueAt(1, 4)},
                {data.getModel().getValueAt(2, 0), data.getModel().getValueAt(2, 1),data.getModel().getValueAt(2, 2), data.getModel().getValueAt(2, 3), data.getModel().getValueAt(2, 4)},
                {data.getModel().getValueAt(3, 0), data.getModel().getValueAt(3, 1),data.getModel().getValueAt(3, 2), data.getModel().getValueAt(3, 3), data.getModel().getValueAt(3, 4)},
                {data.getModel().getValueAt(4, 0), data.getModel().getValueAt(4, 1),data.getModel().getValueAt(4, 2), data.getModel().getValueAt(4, 3), data.getModel().getValueAt(4, 4)},
                {data.getModel().getValueAt(5, 0), data.getModel().getValueAt(5, 1),data.getModel().getValueAt(5, 2), data.getModel().getValueAt(5, 3), data.getModel().getValueAt(5, 4)},
                {data.getModel().getValueAt(6, 0), data.getModel().getValueAt(6, 1),data.getModel().getValueAt(6, 2), data.getModel().getValueAt(6, 3), data.getModel().getValueAt(6, 4)},
                {data.getModel().getValueAt(7, 0), data.getModel().getValueAt(7, 1),data.getModel().getValueAt(7, 2), data.getModel().getValueAt(7, 3), data.getModel().getValueAt(7, 4)}
            },
            new String [] {
                "ID", "Panjang (X1)", "Tinggi (X2)", "Lebar (X3)", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(datalatih);
        if (datalatih.getColumnModel().getColumnCount() > 0) {
            datalatih.getColumnModel().getColumn(0).setResizable(false);
            datalatih.getColumnModel().getColumn(1).setResizable(false);
            datalatih.getColumnModel().getColumn(2).setResizable(false);
            datalatih.getColumnModel().getColumn(3).setResizable(false);
            datalatih.getColumnModel().getColumn(4).setResizable(false);
            datalatih.getColumnModel().getColumn(4).setHeaderValue("Kelas");
        }

        datauji.setAutoCreateRowSorter(true);
        datauji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {data.getModel().getValueAt(8, 0), data.getModel().getValueAt(8, 1),data.getModel().getValueAt(8, 2), data.getModel().getValueAt(8, 3), data.getModel().getValueAt(8, 4)},
                {data.getModel().getValueAt(9, 0), data.getModel().getValueAt(9, 1),data.getModel().getValueAt(9, 2), data.getModel().getValueAt(9, 3), data.getModel().getValueAt(9, 4)},
                {data.getModel().getValueAt(10, 0), data.getModel().getValueAt(10, 1),data.getModel().getValueAt(10, 2), data.getModel().getValueAt(10, 3), data.getModel().getValueAt(10, 4)},
                {data.getModel().getValueAt(11, 0), data.getModel().getValueAt(11, 1),data.getModel().getValueAt(11, 2), data.getModel().getValueAt(11, 3), data.getModel().getValueAt(11, 4)}
            },
            new String [] {
                "ID", "Panjang (X1)", "Tinggi (X2)", "Lebar (X3)", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(datauji);
        if (datauji.getColumnModel().getColumnCount() > 0) {
            datauji.getColumnModel().getColumn(0).setResizable(false);
            datauji.getColumnModel().getColumn(1).setResizable(false);
            datauji.getColumnModel().getColumn(2).setResizable(false);
            datauji.getColumnModel().getColumn(3).setResizable(false);
            datauji.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel4.setText("Data set Data_Latih");

        jLabel5.setText("Data set Data_Uji");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(392, 392, 392))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 163, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data awal", jPanel2);

        jLabel2.setText("Data Latih");

        normaluji.setAutoCreateRowSorter(true);
        normaluji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, null, null, null, null},
                {2, null, null, null, null},
                {3, null, null, null, null},
                {4, null, null, null, null}
            },
            new String [] {
                "ID", "Panjang (X1)", "Tinggi (X2)", "Lebar (X3)", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(normaluji);
        if (normaluji.getColumnModel().getColumnCount() > 0) {
            normaluji.getColumnModel().getColumn(0).setResizable(false);
            normaluji.getColumnModel().getColumn(1).setResizable(false);
            normaluji.getColumnModel().getColumn(2).setResizable(false);
            normaluji.getColumnModel().getColumn(3).setResizable(false);
            normaluji.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel3.setText("Data Uji");

        normallatih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {1, null, null, null, null},
                {2, null, null, null, null},
                {3, null, null, null, null},
                {4, null, null, null, null},
                {5, null, null, null, null},
                {6, null, null, null, null},
                {7, null, null, null, null},
                {8, null, null, null, null}
            },
            new String [] {
                "ID", "Panjang (X1)", "Tinggi (X2)", "Lebar (X3)", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(normallatih);

        jButton1.setText("Tampilkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(615, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("normalisasi", jPanel1);

        Dinput.setText("2");

        jLabel6.setText("D");

        lamdainput.setText("0.5");
        lamdainput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamdainputActionPerformed(evt);
            }
        });

        jLabel7.setText("Lamda");

        jLabel8.setText("Konstanta");

        konstanta.setText("0.01");

        jToggleButton1.setText("Hitung kernel");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Epsilon");

        jLabel10.setText("Alpha");

        jLabel11.setText("C");

        Cinput.setText("1");
        Cinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CinputActionPerformed(evt);
            }
        });

        alpaawal.setText("0");
        alpaawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alpaawalActionPerformed(evt);
            }
        });

        epsiloninput.setText("0.001");
        epsiloninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epsiloninputActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setText("banyak iterasi");

        itermax.setText("100");

        jToggleButton2.setText("Process");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Kernel polinomial d");

        kernel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(kernel1);
        if (kernel1.getColumnModel().getColumnCount() > 0) {
            kernel1.getColumnModel().getColumn(0).setResizable(false);
            kernel1.getColumnModel().getColumn(1).setResizable(false);
            kernel1.getColumnModel().getColumn(2).setResizable(false);
            kernel1.getColumnModel().getColumn(3).setResizable(false);
            kernel1.getColumnModel().getColumn(4).setResizable(false);
            kernel1.getColumnModel().getColumn(5).setResizable(false);
            kernel1.getColumnModel().getColumn(6).setResizable(false);
            kernel1.getColumnModel().getColumn(7).setResizable(false);
            kernel1.getColumnModel().getColumn(8).setResizable(false);
        }

        Thesian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane12.setViewportView(Thesian);
        if (Thesian.getColumnModel().getColumnCount() > 0) {
            Thesian.getColumnModel().getColumn(0).setResizable(false);
            Thesian.getColumnModel().getColumn(1).setResizable(false);
            Thesian.getColumnModel().getColumn(2).setResizable(false);
            Thesian.getColumnModel().getColumn(3).setResizable(false);
            Thesian.getColumnModel().getColumn(4).setResizable(false);
            Thesian.getColumnModel().getColumn(5).setResizable(false);
            Thesian.getColumnModel().getColumn(6).setResizable(false);
            Thesian.getColumnModel().getColumn(7).setResizable(false);
            Thesian.getColumnModel().getColumn(8).setResizable(false);
        }

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setText("Matrix Hessian");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(konstanta, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addComponent(lamdainput)
                                .addComponent(Dinput))
                            .addComponent(jToggleButton1))
                        .addGap(110, 110, 110)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(itermax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(epsiloninput, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alpaawal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cinput, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton2)
                        .addGap(582, 582, 582))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(469, 469, 469))))))
            .addComponent(jSeparator2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Dinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lamdainput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(konstanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Cinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(alpaawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(epsiloninput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(itermax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addComponent(jSeparator4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("sequential training", jPanel3);

        jLabel15.setText("Ei");

        Tei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Ei", "Alpha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Tei);

        jLabel16.setText("Nilai WX+ dan WX-");

        Twx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "WX-", "WX+"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(Twx);
        if (Twx.getColumnModel().getColumnCount() > 0) {
            Twx.getColumnModel().getColumn(0).setResizable(false);
            Twx.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel17.setText("Nilai X- dan X+");

        Txminxpos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "", "X-", "X+"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane13.setViewportView(Txminxpos);
        if (Txminxpos.getColumnModel().getColumnCount() > 0) {
            Txminxpos.getColumnModel().getColumn(1).setResizable(false);
        }

        Tfx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Kelas awal", "Hasil f(x)"
            }
        ));
        jScrollPane14.setViewportView(Tfx);

        jLabel18.setText("Nilai f(x)");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setText("NILAI BIAS");

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        nilaibias.setEditable(false);
        nilaibias.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        nilaibias.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nilaibias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaibiasActionPerformed(evt);
            }
        });

        pengumuman.setText("Tabel diatas menunjukkan kelas awal dan kelas hasil perhitungan menggunakan SVM untuk data UJI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nilaibias)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(454, 454, 454))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(pengumuman)
                                .addGap(42, 42, 42))))))
            .addComponent(jSeparator5)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pengumuman)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator6))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(nilaibias, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(97, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("iterasi", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nilaibiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaibiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaibiasActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        //alpha & ei
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            Tei.getModel().setValueAt(data.getModel().getValueAt(i, 0), i, 0);
            Tei.getModel().setValueAt(ei_alpha[i][0], i, 1);
            Tei.getModel().setValueAt(ei_alpha[i][1], i, 2);
        }
        //x -& x+
        System.out.println(kelas[xminxpos[0]]);
        Object xmin = data.getModel().getValueAt(xminxpos[0], 0);
        Object xpos = data.getModel().getValueAt(xminxpos[1], 0);
        Txminxpos.getModel().setValueAt("ID", 0, 0);
        Txminxpos.getModel().setValueAt(xmin, 0, 1);
        Txminxpos.getModel().setValueAt(xpos, 0, 2);
        //wx- wx+
        for (int i = 0; i < Twx.getModel().getRowCount() - 1; i++) {
            Twx.getModel().setValueAt(data.getModel().getValueAt(i, 0), i, 0);
            Twx.getModel().setValueAt(wxminwxpos[i][0], i, 2);
            Twx.getModel().setValueAt(wxminwxpos[i][1], i, 1);

        }
        Twx.getModel().setValueAt("Jumlah", Twx.getModel().getRowCount() - 1, 0);
        Twx.getModel().setValueAt(wxminwxpos[Twx.getModel().getRowCount() - 1][1], Twx.getModel().getRowCount() - 1, 1);
        Twx.getModel().setValueAt(wxminwxpos[Twx.getModel().getRowCount() - 1][0], Twx.getModel().getRowCount() - 1, 2);
        //bias
        nilaibias.setText(String.valueOf(Nbias));
        //hasil
        for (int i = 0; i < datauji.getModel().getRowCount(); i++) {
            Tfx.getModel().setValueAt(datauji.getModel().getValueAt(i, 0), i, 0);
            Tfx.getModel().setValueAt(datauji.getModel().getValueAt(i, 4), i, 1);
            Tfx.getModel().setValueAt(hasil[i], i, 2);
        }
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void epsiloninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epsiloninputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epsiloninputActionPerformed

    private void alpaawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alpaawalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alpaawalActionPerformed

    private void CinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CinputActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        //kernel
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            kernel1.getModel().setValueAt(data.getModel().getValueAt(i, 0), i, 0);
        }
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            for (int j = 0; j < normallatih.getModel().getRowCount(); j++) {
                kernel1.getModel().setValueAt(kernel_latih[i][j], i, j + 1);
            }
        }
        //hessian
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            Thesian.getModel().setValueAt(data.getModel().getValueAt(i, 0), i, 0);
        }
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            for (int j = 0; j < normallatih.getModel().getRowCount(); j++) {
                Thesian.getModel().setValueAt(hessian[i][j], i, j + 1);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void lamdainputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamdainputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamdainputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("normalisasi");
        //data latih
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            normallatih.getModel().setValueAt(data.getModel().getValueAt(i, 0), i, 0);
        }
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            normallatih.getModel().setValueAt(normallatih1[i][0], i, 1);
            normallatih.getModel().setValueAt(normallatih1[i][1], i, 2);
            normallatih.getModel().setValueAt(normallatih1[i][2], i, 3);
        }
        for (int i = 0; i < normallatih.getModel().getRowCount(); i++) {
            normallatih.getModel().setValueAt(data.getModel().getValueAt(i, 4), i, 4);
        }
        //data uji
        for (int i = 0; i < normaluji.getModel().getRowCount(); i++) {
            normaluji.getModel().setValueAt(datauji.getModel().getValueAt(i, 0), i, 0);
        }
        for (int i = 0; i < normaluji.getModel().getRowCount(); i++) {
            normaluji.getModel().setValueAt(normaluji1[i][0], i, 1);
            normaluji.getModel().setValueAt(normaluji1[i][1], i, 2);
            normaluji.getModel().setValueAt(normaluji1[i][2], i, 3);
        }
        for (int i = 0; i < normaluji.getModel().getRowCount(); i++) {
            normaluji.getModel().setValueAt(datauji.getModel().getValueAt(i, 4), i, 4);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    static mobilview view = new mobilview();
    static Object normallatih1[][], normaluji1[][];
    static double kernel_latih[][], hessian[][], ei_alpha[][], kernelxminxpos[][], wxminwxpos[][], Nbias;
    static int kelas[], xminxpos[], hasil[], kelasuji[];
    static int C = Integer.valueOf(view.Cinput.getText());
    static int D = Integer.valueOf(view.Dinput.getText());

    public static void main(String args[]) {
        mobil baru = new mobil();
        int itermax = Integer.valueOf(view.itermax.getText());

        double lamda = Double.valueOf(view.lamdainput.getText());
        double alpa_awal = Double.valueOf(view.alpaawal.getText());
        double epsilon = Double.valueOf(view.epsiloninput.getText());
        double konstanta = Double.valueOf(view.konstanta.getText());
        double latih[][] = new double[view.datalatih.getModel().getRowCount()][view.datalatih.getModel().getColumnCount() - 2];
        double uji[][] = new double[view.datauji.getModel().getRowCount()][view.datauji.getModel().getColumnCount() - 2];
        kelas = new int[view.data.getModel().getRowCount()];
        kelasuji = new int[view.datauji.getModel().getRowCount()];
        kernel_latih = new double[view.datalatih.getModel().getRowCount()][view.datalatih.getModel().getRowCount()];
        hessian = new double[view.datalatih.getModel().getRowCount()][view.datalatih.getModel().getRowCount()];
        normallatih1 = new Object[latih.length][latih[0].length];
        normaluji1 = new Object[uji.length][uji[0].length];
        ei_alpha = new double[hessian.length][2];
        xminxpos = new int[2];
        kernelxminxpos = new double[hessian.length][2];
        wxminwxpos = new double[hessian.length][2];
        hasil = new int[uji.length];
        for (int i = 0; i < kelas.length; i++) {
            kelas[i] = (int) view.data.getModel().getValueAt(i, 4);
        }
        for (int i = 0; i < kelasuji.length; i++) {
            kelasuji[i] = (int) view.datauji.getModel().getValueAt(i, 4);
        }
        //data latih
        int index;
        for (int i = 0; i < latih.length; i++) {
            index = 1;
            for (int j = 0; j < latih[0].length; j++) {
                latih[i][j] = (double) view.datalatih.getModel().getValueAt(i, index);
                index++;
            }
        }
        System.out.println("datalatih");
        for (int i = 0; i < latih.length; i++) {
            for (int j = 0; j < latih[0].length; j++) {
                System.out.print(latih[i][j] + " ");
            }
            System.out.println("");
        }
        normallatih1 = baru.normalisasiminMax(latih);
        //data uji
        for (int i = 0; i < uji.length; i++) {
            index = 1;
            for (int j = 0; j < uji[0].length; j++) {
                uji[i][j] = (double) view.datauji.getModel().getValueAt(i, index);
                index++;
            }
        }
        System.out.println("data uji");
        for (int i = 0; i < uji.length; i++) {
            for (int j = 0; j < uji[0].length; j++) {
                System.out.print(uji[i][j] + " ");
            }
            System.out.println("");
        }

        normaluji1 = baru.normalisasiminMax(uji);
        //cari kernel
        kernel_latih = baru.carikernel(normallatih1, D);
        //cari hessian
        hessian = baru.carihesian(kernel_latih, lamda, kelas);
        //sequential
        ei_alpha = baru.sequensial_training(hessian, itermax, C, alpa_awal, epsilon, konstanta);
        //xminxpos
        xminxpos = baru.carixminxpos(ei_alpha, kelas);
        //kernelxminxpos
        kernelxminxpos = baru.kernelxminxpos(normallatih1, D, xminxpos);
        //wxmin wxpos
        wxminwxpos = baru.hitungwx(kernelxminxpos, kelas, ei_alpha);
        //bias
        Nbias = baru.nilaibias(wxminwxpos);
        //hasil f(x)
        hasil = baru.hitungfx(normallatih1, normaluji1, D, kelasuji, ei_alpha, Nbias);

        //
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mobilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mobilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mobilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mobilview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mobilview().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cinput;
    private javax.swing.JTextField Dinput;
    private javax.swing.JTable Tei;
    private javax.swing.JTable Tfx;
    private javax.swing.JTable Thesian;
    private javax.swing.JTable Twx;
    private javax.swing.JTable Txminxpos;
    private javax.swing.JTextField alpaawal;
    private javax.swing.JTable data;
    private javax.swing.JTable datalatih;
    private javax.swing.JTable datauji;
    private javax.swing.JTextField epsiloninput;
    private javax.swing.JTextField itermax;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable kernel1;
    private javax.swing.JTextField konstanta;
    private javax.swing.JTextField lamdainput;
    private javax.swing.JTextField nilaibias;
    private javax.swing.JTable normallatih;
    private javax.swing.JTable normaluji;
    private javax.swing.JLabel pengumuman;
    // End of variables declaration//GEN-END:variables
}
